/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer_package;
import fdms.dbconn;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.ImageIcon;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
public class orders extends javax.swing.JFrame {

    int orderId;
    String restId,deliveryId,status;
    dbconn db;
    String custId;
    ArrayList<String> orders_list;
    
    
    public orders(String custid) {
        custId=custid;
        db=new dbconn();
        orders_list=new ArrayList<String>();
       
        
        initComponents();
        set_latest();
        
    }
    
    public void set_latest()
    {
        String st="";
        ResultSet rs;
        OTable.removeAll();
        DefaultTableModel tblModel=(DefaultTableModel)OTable.getModel();
        tblModel.setRowCount(0);
        try {
            rs= db.stmt.executeQuery("SELECT * FROM ORDERS WHERE CUSTID='"+custId+"' ORDER BY DATETIME DESC");
            if(rs.next())
            {
                recentPanel.setVisible(true);
                orderId=Integer.parseInt(rs.getString(1));
                restId=rs.getString(4);
                st=rs.getString(6)+" ";
                System.out.println(st);
                System.out.println(orderId);
                JorderId.setText("#"+orderId);
                status=rs.getString(7);
                deliveryId=rs.getString(3);
                JPrice.setText("₹"+st);
                
            ImageIcon img=new ImageIcon("src/imgs/rest_imgs/"+restId+".jpg");
            Image image = img.getImage();
            Image newimg = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newimg);
            RImg.setIcon(newIcon);
            
            if(status.equals("Ready"))
            {
                stage1.setEnabled(true);
                stage2.setEnabled(false);
                stage3.setEnabled(false);

            }
            else if(status.equals("Picked Up"))
            {
                stage1.setEnabled(true);
                stage2.setEnabled(true);
                stage2.setForeground(Color.black);
                stage3.setEnabled(false);
             
            }
            else if(status.equals("Delivered"))
            {
                stage1.setEnabled(true);
                stage2.setEnabled(true);
                stage3.setEnabled(true);
                stage2.setForeground(Color.black);
                stage3.setForeground(Color.black);
            }

            }
            else
            {
               recentPanel.setVisible(false);
            }
            while(rs.next())
            {   
                
                    Statement st2=db.conn.createStatement();
                    ResultSet r2=st2.executeQuery("SELECT NAME FROM RESTAURANT WHERE RESTID='"+rs.getString(4)+"'");
                    if(r2.next())
                    {
                        String Tdata[]={rs.getString(1),r2.getString(1),'₹'+rs.getString(6),rs.getString(7)};

                        tblModel.addRow(Tdata);
                  
                }
                orders_list.add(rs.getString(1));
            }
            rs=db.stmt.executeQuery("SELECT NAME,PHONE FROM DELIVERYBOY WHERE USERNAME='"+deliveryId+"'");
            if(rs.next())
            {
                DName.setText(rs.getString(1).toUpperCase()+" is on the way with your food");
                Dphone.setText(rs.getString(2));
                
            }
        
        System.out.println(orders_list);
            
        } catch (SQLException ex) {
            Logger.getLogger(orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            rs=db.stmt.executeQuery("Select Name from Restaurant where Restid='"+restId+"'");
            if(rs.next())
            {
                restName.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(orders.class.getName()).log(Level.SEVERE, null, ex);
        }

        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recentPanel = new javax.swing.JPanel();
        RImg = new javax.swing.JLabel();
        restName = new javax.swing.JLabel();
        JorderId = new javax.swing.JLabel();
        JPrice = new javax.swing.JLabel();
        stage3 = new javax.swing.JButton();
        stage1 = new javax.swing.JButton();
        stage2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DName = new javax.swing.JLabel();
        Dphone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OTable = new javax.swing.JTable();
        BRefresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 750));
        setResizable(false);

        recentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        recentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RImg.setText("jLabel3");
        recentPanel.add(RImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 90, 90));

        restName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        restName.setText("Rest");
        recentPanel.add(restName, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 34, 230, 29));

        JorderId.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        JorderId.setForeground(new java.awt.Color(51, 51, 51));
        JorderId.setText("1234323");
        recentPanel.add(JorderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 58, 230, -1));

        JPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JPrice.setText("24 Items | 500");
        recentPanel.add(JPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, 20));

        stage3.setBackground(new java.awt.Color(51, 255, 51));
        stage3.setForeground(new java.awt.Color(153, 153, 153));
        stage3.setText("Order Delivered");
        stage3.setEnabled(false);
        stage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stage3ActionPerformed(evt);
            }
        });
        recentPanel.add(stage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 140, 40));

        stage1.setBackground(new java.awt.Color(255, 102, 102));
        stage1.setForeground(new java.awt.Color(0, 0, 0));
        stage1.setText("Food is being prepared");
        stage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stage1ActionPerformed(evt);
            }
        });
        recentPanel.add(stage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 40));

        stage2.setBackground(new java.awt.Color(255, 102, 0));
        stage2.setForeground(new java.awt.Color(153, 153, 153));
        stage2.setText("Food is on the way");
        stage2.setEnabled(false);
        stage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stage2ActionPerformed(evt);
            }
        });
        recentPanel.add(stage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 40));

        jLabel5.setText("----------------------");
        recentPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel6.setText("----------------------");
        recentPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        DName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DName.setText("is on the way with your food");

        Dphone.setText("8989787889");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dphone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dphone)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        recentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 250, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Your orders:");

        jLabel2.setText("Most recent Order");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Previous Orders:");

        OTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "Restaurant", "Total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OTable.setRowHeight(40
        );
        OTable.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(OTable);
        if (OTable.getColumnModel().getColumnCount() > 0) {
            OTable.getColumnModel().getColumn(0).setResizable(false);
            OTable.getColumnModel().getColumn(1).setResizable(false);
            OTable.getColumnModel().getColumn(2).setResizable(false);
            OTable.getColumnModel().getColumn(3).setResizable(false);
        }

        BRefresh.setText("Refresh");
        BRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRefreshActionPerformed(evt);
            }
        });

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BRefresh)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stage3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stage3ActionPerformed

    private void stage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stage1ActionPerformed

    private void stage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stage2ActionPerformed

    private void BRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRefreshActionPerformed
        set_latest();
    }//GEN-LAST:event_BRefreshActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       cust_home home=new cust_home(custId);
        home.setVisible(true);
        try {
            db.end();
        } catch (SQLException ex) {
            Logger.getLogger(orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRefresh;
    private javax.swing.JLabel DName;
    private javax.swing.JLabel Dphone;
    private javax.swing.JLabel JPrice;
    private javax.swing.JLabel JorderId;
    private javax.swing.JTable OTable;
    private javax.swing.JLabel RImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel recentPanel;
    private javax.swing.JLabel restName;
    private javax.swing.JButton stage1;
    private javax.swing.JButton stage2;
    private javax.swing.JButton stage3;
    // End of variables declaration//GEN-END:variables

}
